package modelo.ud3;
// Generated 19 mar 2023 11:35:06 by Hibernate Tools 4.3.6.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AccMovement generated by hbm2java
 */
@Entity
@Table(name = "ACC_MOVEMENT", catalog = "empresa_prueba_ud3")
public class AccMovement implements java.io.Serializable {

	private Integer accountMovId;
	private Account accountDestino;
	private Account accountOrigen;
	private BigDecimal amount;
	private LocalDateTime datetime;

	public AccMovement() {
	}

	public AccMovement(Account accountByAccountDestId, Account accountByAccountOriginId, BigDecimal amount,
			LocalDateTime datetime) {
		this.accountDestino = accountByAccountDestId;
		this.accountOrigen = accountByAccountOriginId;
		this.amount = amount;
		this.datetime = datetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACCOUNT_MOV_ID", unique = true, nullable = false)
	public Integer getAccountMovId() {
		return this.accountMovId;
	}

	public void setAccountMovId(Integer accountMovId) {
		this.accountMovId = accountMovId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_DEST_ID", nullable = false)
	public Account getAccountDestino() {
		return this.accountDestino;
	}

	public void setAccountDestino(Account accountByAccountDestId) {
		this.accountDestino = accountByAccountDestId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCOUNT_ORIGIN_ID", nullable = false)
	public Account getAccountOrigen() {
		return this.accountOrigen;
	}

	public void setAccountOrigen(Account accountByAccountOriginId) {
		this.accountOrigen = accountByAccountOriginId;
	}

	@Column(name = "AMOUNT", nullable = false, scale = 4)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	
	@Column(name = "DATETIME", nullable = false, length = 23)
	public LocalDateTime getDatetime() {
		return this.datetime;
	}

	public void setDatetime(LocalDateTime datetime) {
		this.datetime = datetime;
	}

	@Override
	public String toString() {
		return "AccMovement [accountMovId=" + accountMovId + ", accountDestino=" + accountDestino.getAccountno() + ", accountOrigen="
				+ accountOrigen.getAccountno() + ", amount=" + amount + ", datetime=" + datetime + "]";
	}

	
	
}
