package modelo.ud3;
// Generated 19 mar 2023 11:35:06 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENT", catalog = "empresa_prueba_ud3")
public class Departamento implements java.io.Serializable {

	private Integer deptno;
	private String dname;
	private String loc;
	private Set<Empleado> employees = new HashSet<Empleado>(0);

	public Departamento() {
	}

	public Departamento(String dname, String loc, Set<Empleado> employees) {
		this.dname = dname;
		this.loc = loc;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DEPTNO", unique = true, nullable = false)
	public Integer getDeptno() {
		return this.deptno;
	}

	public void setDeptno(Integer deptno) {
		this.deptno = deptno;
	}

	@Column(name = "DNAME", length = 20)
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	@Column(name = "LOC", length = 20)
	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "department")
	public Set<Empleado> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Empleado> employees) {
		this.employees = employees;
	}

}
